name: Version

on: [push]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versionstring.outputs.version }}
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Assemble version string on master
      id: versionstring
      if: steps.gitversion.outputs.branchName == "master"
      run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}"
    - name: Assemble version string on branch
      id: versionstring
      if: steps.gitversion.outputs.branchName != "master"
      run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.escapedBranchName }}"

  package:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - name: Display version
      run: |
        echo Version: ${{ needs.version.outputs.version }}
