name: Version

on: [push]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versionstring.outputs.version }}
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Assemble version string on master
      id: v1
      if: steps.gitversion.outputs.branchName == 'master' || steps.gitversion.outputs.branchName == 'main'
      run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}"
    - name: Assemble version string on branch
      id: v2
      if: steps.gitversion.outputs.branchName != 'master' && steps.gitversion.outputs.branchName != 'main'
      run: echo "::set-output name=version::${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.escapedBranchName }}"
    - name: Output version string
      id: v3
      run: echo "::set-output name=version::${{ steps.v1.outputs.version }}${{ steps.v2.outputs.version }}"
    - name: Output build number
      id: buildnumber
      if: steps.gitversion.outputs.buildMetaData != ''
      run: echo "::set-output name=build::-${{ steps.gitversion.outputs.buildMetaData }}"
    - name: Output final version string
      id: versionstring
      run: echo "::set-output name=version::${{ steps.v3.outputs.version }}${{ steps.buildnumber.outputs.build }}"

  package:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - name: Display version
      run: |
        echo Version: ${{ needs.version.outputs.version }}
